name: base-py
version: 0.0.0
homepage: https://github.com/morloclib/base-py
synopsis: Base types and functions for Python3
description: Lots of detail about all this
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloclib/base-py
bug-reports: https://github.com/morloclib/base-py
